# GitHub link

https://github.com/2026726-dotcom/STDA

# CA 1: Obesity levels according to eating habits and physical activity

## This dataset will be analysed using statistics.
## The dataset shows some features that can be used to determinar obesity

In [10]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [11]:
data = pd.read_csv('dataset.csv') #This line is for reading the dataset
data.head(10) # to read the first 5 rows

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II
5,Male,29.0,1.62,53.0,no,yes,2.0,3.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Automobile,Normal_Weight
6,Female,23.0,1.50,55.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0,0.0,Sometimes,Motorbike,Normal_Weight
7,Male,22.0,1.64,53.0,no,no,2.0,3.0,Sometimes,no,2.0,no,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
8,Male,24.0,1.78,64.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0,1.0,Frequently,Public_Transportation,Normal_Weight
9,Male,22.0,1.72,68.0,yes,yes,2.0,3.0,Sometimes,no,2.0,no,1.0,1.0,no,Public_Transportation,Normal_Weight

In [12]:
data.shape # number of rows and columns

(2111, 17)

In [13]:
data.isnull().sum() #to show null values

Gender                            0
Age                               0
Height                            0
Weight                            0
family_history_with_overweight    0
FAVC                              0
FCVC                              0
NCP                               0
CAEC                              0
SMOKE                             0
CH2O                              0
SCC                               0
FAF                               0
TUE                               0
CALC                              0
MTRANS                            0
NObeyesdad                        0
dtype: int64

In [14]:
data.info() #to see type of values in each feature (numerical and categorical)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Gender                          2111 non-null   object
 1   Age                             2111 non-null   float64
 2   Height                          2111 non-null   float64
 3   Weight                          2111 non-null   float64
 4   family_history_with_overweight  2111 non-null   object
 5   FAVC                            2111 non-null   object
 6   FCVC                            2111 non-null   float64
 7   NCP                             2111 non-null   float64
 8   CAEC                            2111 non-null   object
 9   SMOKE                           2111 non-null   object
 10  CH2O                            2111 non-null   float64
 11  SCC                             2111 non-null   object
 12  FAF                             2111 non-null   float64
 13  TUE                             2111 non-null   float64
 14  CALC                            2111 non-null   object
 15  MTRANS                          2111 non-null   object
 16  NObeyesdad                      2111 non-null   object
dtypes: float64(8), object(9)
memory usage: 280.5+ KB

### Acronimes


FAVC: Do you eat high caloric food frequently?

FCVC: Do you usually eat vegetables in your meals?

NCP: How many main meals do you have daily?

CAEC: Do you eat any food between meals?

SMOKE: 	Do you smoke?

CH20: How much water do you drink daily?

SCC: Do you monitor the calories you eat daily?

FAF: How often do you have physical activity?

TUE: How much time do you use technological devices?

CALC: How often do you drink alcohol?

MTRANS: Which transportation do you usually use?

NObeyesdad: Obesity level

### 1. Summarize your dataset clearly, using relevant descriptive statistics and appropriate plots. These should be carefully motivated and justified and clearly presented. You should critically analyse your findings, in addition to including the necessary Python code, output and plots in the report. You are required to plot at least three graphs. [0-35]

In [15]:
data.describe() #This line gives a summary statistics of the numerical features.

,Age,Height,Weight,FCVC,NCP,CH2O,FAF,TUE
count,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000
mean,24.312600,1.701677,86.586058,2.419043,2.685628,2.008011,1.010298,0.657866
std,6.345968,0.093305,26.191172,0.533927,0.778039,0.612953,0.850592,0.608927
min,14.000000,1.450000,39.000000,1.000000,1.000000,1.000000,0.000000,0.000000
25%,19.947192,1.630000,65.473343,2.000000,2.658738,1.584812,0.124505,0.000000
50%,22.777890,1.700499,83.000000,2.385502,3.000000,2.000000,1.000000,0.625350
75%,26.000000,1.768464,107.430682,3.000000,3.000000,2.477420,1.666678,1.000000
max,61.000000,1.980000,173.000000,3.000000,4.000000,3.000000,3.000000,2.000000

1. Measures of central tendency 
    - Mean
    - Median
    - Mode

In [16]:
#Mean and Median for NCP and CH2O
meanNCP = data["NCP"].mean()
meanNCP = f"{meanNCP:.2f}"
meanCH2O = data["CH2O"].mean()
meanCH2O = f"{meanCH2O:.2f}"
medianNCP = data["NCP"].median()
medianCH2O = data["CH2O"].median()

print('Mean NCP: ', meanNCP,'Mean CH2O: ', meanCH2O,'\n'
      'Median NCP: ', medianNCP, 'Median CH2O: ', medianCH2O)

Mean NCP:  2.69 Mean CH2O:  2.01
Median NCP:  3.0 Median CH2O:  2.0

In [17]:
#conversion float to integer
 
#Mode for Age and TUE
modeNCP = data['NCP'].mode()
modeNCP = int(modeNCP)
modeCH2O = data["CH2O"].mode()
modeCH2O = int(modeCH2O)
print('Mode NCP: ', modeNCP,'Mode CH2O: ', modeCH2O)

Mode NCP:  3 Mode CH2O:  2

C:\Users\HP\AppData\Local\Temp\ipykernel_19596\646670990.py:5: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  modeNCP = int(modeNCP)
C:\Users\HP\AppData\Local\Temp\ipykernel_19596\646670990.py:7: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  modeCH2O = int(modeCH2O)